elitegolfschools:
  handle: "@elitegolfschools"
  channel_id: "UCePCyXFuu_B-8bPuY-cvn4Q"
  aliases:
    - egs
    - riley
    - elite

milolinesgolf:
  handle: "@milolinesgolf"
  channel_id: "UC6W3WoE15mnJNYFVh8-ksJw"
  aliases:
    - mlg
    - milo
