elitegolfschools:
  enabled: true
  handle: "@elitegolfschools"
  channel_id: "UCePCyXFuu_B-8bPuY-cvn4Q"
  vector_store_ids:
    longform:
      all: vs_695d6e3ee54881918d4d5c276329d71e  # Catch-all store for RAG fallback (NOT for static context)
      ball_control: vs_695d6e00d87881918c74efd73f04630c
      dynamic_exercises: vs_695d6e0b8d908191868065dd65a9fdfa
      full_swing: vs_695d6e191bb08191ad9b7002fda0650e
      mental_game: vs_695d6e260614819194eeebc26ae22960
      putting: vs_695d6e2eef3481918ed52e41c9ccf61b
      short_game: vs_695d6e379cfc819196e3885da79d9979
  aliases:
    - egs
    - riley
    - elite
  constant_context_videos:
    full_swing:
      - 7H_Io-ihcTA
      - hQjclbX8HSg
      - 3Mhn9DPFK3M
      - Clax19sQoBY
      - 69F-qhOnPw8
      - 1ZDgatxIO5c
      - 8SoRSLi2qGE
      - Q1IJlYEGWPI
      - z-JBfmq7aMs
      - EpCsPRrFg2I
      - LOpmTtz5VTE
      - bJWrOT0SG7U
      - 69SCQq1t_Og
      - 4JlWF6uc8_k
      - aK-EASxY_kM
      - AdCgluJHsns
      - LbQWUXq_vGc
      - ZzkbHw4NoNE
      - FRyqMMpfQ0A
      - litj4sqgRD8
      - 7cAa9JPT9z0
      - nkUhiS18VT0
      - db1iz6Zzn2c
      - Ad1c794atTA
      - OGSJ6vtXEWg
      - 07ZxDD-pXgo
      - wi2KruC7WNA
      - 0LI6j6tAfZc
      - R2cA2iseTEM
      - yNFFw40YzsQ
      - r2fj-XogeMk
      - sewCowJnyZc
    short_game:
      - O3--ULMwXJQ
      - z7aupHW5bhI
      - 2CwizITuaHk
      - SDAPXFfuzIE
    putting:
      - ES1-leFYZFM
      - v5Qem_Wxb14
    ball_control:
      - V26gyfvlXQQ
      - sfyQhLzjKuU
      - -eYJtkacBIU
      - _I2_bsE8Uog
      - lUM0XNyKR7k
      - mNL0fbccnkQ
      - PencmKLQjq8
      - Hz6ECbTXjWA
      - 1Pj28UxpCGc
      - h1qP2Z2EDH4
      - zKwdJkxWBH0
      - zSLntB0Q4K4
      - 2CwizITuaHk
      - -eKQD-9_2qA
      - loMCG3fWGXo
      - 84Vr2ZHafxU
    mental_game:
      - -eKQD-9_2qA
      - 12D4kk0UkBY
      - 7ygGWr6kwh0
    dynamic_exercises:
      - s46IxC8H8dQ
      - bJWrOT0SG7U
      - 69SCQq1t_Og
      - 4JlWF6uc8_k
      - R2cA2iseTEM
      - r2fj-XogeMk
  instructions: |
    You are Riley Andrews from Elite Golf Schools.
    Your coaching style is direct, "aha" focused, and energetic.
    Some might describe you as intense.
    You love healthy movement (biomechanics), and build a golf swing to fit these principles.
    Viktor Hovland is one of your favorite movers in golf.

    When answering questions, you will follow this structure:
    1. Repeat the question in brief to to let the user see you understood correctly.
    2. Sumarize your opinion up front, then provide supporting details.
    3. Give reference to healthy movement patterns to explain your preferences in golf swing movement.
    4. Finally, give a drill or two if relevant ones are present in your knowledge base.

    NEVER invent or make up answers or drills.
    Stick to your knowledge base.
    If your knowledge base does not contain the answer, say "I don't know" or "I don't have that information".

    Here are some catch phrases you often use:
    - Greetings: "What up homie G", "Dang it's great to see you", "Lets rock and roll, homie G."
    - Reactions to questions: "That's a great question", "Oh I could talk for hours on this.", "You ready to get real?"
    - Ending phrases: "Hit some flushers for me", "Flushers inbound , baby"
    - When debunking common misconceptions: "That's total BS", "That's bullshit, bro", "That's not how it works, homie G"

    Aim for 400-500 words in your answers, following the structure above.
    Make sure you read the entire context.

    Output formatting (IMPORTANT):
    Format your answers in markdown, making use of headings, bullet points, and bold text where appropriate.
    Avoid walls of text.
    Enumerate when relevant.


milolinesgolf:
  enabled: false
  handle: "@milolinesgolf"
  channel_id: "UC6W3WoE15mnJNYFVh8-ksJw"
  vector_store_ids:
    longform:
      all: ""  # Catch-all store for RAG fallback (NOT for static context)
      ball_control: ""
      dynamic_exercises: ""
      full_swing: ""
      mental_game: ""
      putting: ""
      short_game: ""
  aliases:
    - mlg
    - milo
  constant_context_videos:
    full_swing:
      - PVxLqLPYF7g
      - qfB8Qb3F_Ck
      - lytmpIqBXkc
      - h3wCa2DYjMA
      - XdHsiosS1mM
      - WSyrtDyiU5A
      - 7chRlcCJCII
      - osX-4KsSvoM
      - BQtsQuLU64I
      - 2p_0ql873jw
      - 4tF9qcxr5pY
      - 1CAV1Uk3rrU
      - __WbfKWY7hE
      - vSv5bEUcYn8
      - afwUR5SeN3E
      - 7XWg_EETIUo
      - HbI5Bjoancw
      - eybNkx8AI2U
      - 0fzowDH_dNs
      - WZb44CpMltU
      - afnIKSTf5fE
      - MTIPOfBvqVU
      - WLpcH8qNvGA
      - vS8kQmZ4Z-U
      - t3bZLQcEVfQ
      - Von7Tnbn-40
      - K-7XYqrP-tk
      - yu8qbzVG3O8
      - 56a-0TIvlsc
      - LG_bxcosXyw
      - 2njNKRvbjf4
      - Id__9Uktkyk
      - UGayulQz4vM
      - b-OLmsLXrqY
      - tJO1Eef6uCs
      - VpRka0vQCWw
      - LC4i5KvkKYQ
      - eXpOLt2U-9w
      - s0Bwq2oZtRI
      - 9LczSFw-Nbo
      - q1xM3wc40Yk
      - X1d82CdunlE
      - YyBJ40vot5I
      - sOJIFrsxblA
      - ao-XbVkzGtw
      - Dm14lnuVlzw
      - FTtJNealDGI
      - 5yJNxV2WJfA
      - NP8xnfCdHz8
      - mNzQ_KSvOg0
      - KqB5jRRbLq0
      - HYvXv6pPy4s
      - nzQv65KRtXk
      - x0t3kQ24Ci4
      - RBm97rgofbk
      - U3WBfm6beOc
      - G7MYsonPzJA
      - EViKA95xQOk
    short_game: []
    putting: []
    ball_control: []
    mental_game: []
    dynamic_exercises: []
  instructions: ""
