# Format: YAML
# Syntax: ENV_VARIABLE: DESCRIPTION
OPENAI__API_KEY: "API key for accessing OpenAI services"

PROXY__USERNAME: "Username for proxy authentication"
PROXY__PASSWORD: "Password for proxy authentication"

YOUTUBE__API_KEY: "API key for accessing YouTube Data API services"

YOUTUBE__EGS__CHANNEL_NAME: "YouTube channel name for EGS content"
YOUTUBE__EGS__CHANNEL_ID: "YouTube channel ID for EGS content"
YOUTUBE__EGS__HANDLE: "YouTube handle for EGS content"

YOUTUBE__MILO__CHANNEL_NAME: "YouTube channel name for Milo Lines Golf content"
YOUTUBE__MILO__CHANNEL_ID: "YouTube channel ID for Milo Lines Golf content"
YOUTUBE__MILO__HANDLE: "YouTube handle for Milo Lines Golf content"
